"""empty message

Revision ID: 2a5a1d039b94
Revises: 4b38a7d53576
Create Date: 2020-03-05 14:40:53.424484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a5a1d039b94'
down_revision = '4b38a7d53576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('recorded_location', sa.String(length=512), nullable=True))
    op.add_column('sample', sa.Column('recorded_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample', 'recorded_time')
    op.drop_column('sample', 'recorded_location')
    # ### end Alembic commands ###
